"""add_confidence_to_tasks

Revision ID: e761d2bedef5
Revises: 214d0b0a04ed
Create Date: 2026-06-10 11:18:10.970609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e761d2bedef5'
down_revision: Union[str, None] = '214d0b0a04ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('confidence', sa.Float(), nullable=False, server_default='0.8'))
    op.alter_column('tasks', 'confidence', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'confidence')
    # ### end Alembic commands ###
